clear; clc; close all;

% Standalone reproduction of the Bland-Altman panels generated by
% LMM_AI_IN.m (Supplementary Figure 1).

script_dir = fileparts(mfilename('fullpath'));
input_file = fullfile(script_dir, 'figure_input_data.csv');

Tinput = readtable(input_file, 'TextType', 'string');
Tinput = Tinput(Tinput.IncludeInAnalysis == 1, :);
devices = ["NIRSIT-X", "INVOS"];
n_boot = 2000;
rng(2026);

results = cell(numel(devices),1);
result_table = table();
point_table = table();

for d = 1:numel(devices)
    Td = Tinput(Tinput.Device == devices(d), :);
    [results{d}, result_row, points] = run_bland_altman(Td, devices(d), n_boot);
    result_table = [result_table; result_row]; %#ok<AGROW>
    point_table = [point_table; points]; %#ok<AGROW>
end

writetable(result_table, fullfile(script_dir, 'supple_figure1_results.csv'));
writetable(point_table, fullfile(script_dir, 'supple_figure1_point_data.csv'));

display_table = table( ...
    result_table.Device, result_table.NObservations, ...
    compose('%.3f', result_table.Bias), ...
    compose('[%.3f, %.3f]', result_table.BiasCI_Lower, result_table.BiasCI_Upper), ...
    compose('%.3f', result_table.LoA_Lower), ...
    compose('%.3f', result_table.LoA_Upper), ...
    compose('[%.3f, %.3f]', result_table.LoA_LowerCI_Lower, result_table.LoA_LowerCI_Upper), ...
    compose('[%.3f, %.3f]', result_table.LoA_UpperCI_Lower, result_table.LoA_UpperCI_Upper), ...
    'VariableNames', {'Device','NObservations','Bias','BiasCI95','LoA_Lower', ...
    'LoA_Upper','LoA_LowerCI95','LoA_UpperCI95'});
writetable(display_table, fullfile(script_dir, 'supple_figure1_display.csv'));

x_all = [results{1}.mean_value; results{2}.mean_value];
y_all = [results{1}.difference; results{2}.difference];
y_reference = [results{1}.bias; results{1}.loa_lower; results{1}.loa_upper; ...
    results{2}.bias; results{2}.loa_lower; results{2}.loa_upper];
x_pad = max((max(x_all)-min(x_all))*0.05, 0.1);
y_pad = max((max([y_all;y_reference])-min([y_all;y_reference]))*0.05, 0.1);
x_limits = [min(x_all)-x_pad, max(x_all)+x_pad];
y_limits = [min([y_all;y_reference])-y_pad, max([y_all;y_reference])+y_pad];

fig = figure('Color', 'w', 'Position', [100 100 1500 650], 'Visible', 'off');
tiledlayout(fig, 1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');
for d = 1:numel(devices)
    ax = nexttile;
    hold(ax, 'on');
    scatter(ax, results{d}.mean_value, results{d}.difference, 90, 'filled', ...
        'MarkerFaceColor', [0.15 0.15 0.15], 'MarkerFaceAlpha', 0.85);
    yline(ax, results{d}.bias, 'r-', 'LineWidth', 3);
    yline(ax, results{d}.loa_lower, 'k--', 'LineWidth', 2.5);
    yline(ax, results{d}.loa_upper, 'k--', 'LineWidth', 2.5);
    xlim(ax, x_limits);
    ylim(ax, y_limits);
    xlabel(ax, 'Mean of SjvO2 and rSO2 (%)');
    ylabel(ax, 'Difference (SjvO2 - rSO2, %)');
    title(ax, sprintf('%s Bland-Altman: bias = %.2f, LoA = [%.2f, %.2f]', ...
        devices(d), results{d}.bias, results{d}.loa_lower, results{d}.loa_upper));
    set(ax, 'LineWidth', 2.2, 'FontSize', 16, 'FontWeight', 'bold', ...
        'TickDir', 'out', 'TickLength', [0.02 0.02], 'Box', 'off');
    grid(ax, 'on');
end
exportgraphics(fig, fullfile(script_dir, 'supple_figure1_reproduced.png'), 'Resolution', 300);
close(fig);


fprintf('Supplementary Figure 1 reproduction complete: %s\n', script_dir);

function [result, output_row, points] = run_bland_altman(Td, device, n_boot)
    Y = Td.rSO2;       % source Excel column 2
    z = Td.SjvO2;      % source Excel column 3
    subject = Td.SubjectID;
    mean_value = (Y+z)/2;
    difference = Y-z;
    bias = mean(difference);
    sd_difference = std(difference,1);
    loa_lower = bias-1.96*sd_difference;
    loa_upper = bias+1.96*sd_difference;

    subjects = unique(subject);
    n_subjects = numel(subjects);
    bias_boot = nan(n_boot,1);
    loa_lower_boot = nan(n_boot,1);
    loa_upper_boot = nan(n_boot,1);

    for b = 1:n_boot
        sampled_subjects = subjects(randi(n_subjects,n_subjects,1));
        boot_difference = [];
        for j = 1:n_subjects
            idx = subject == sampled_subjects(j);
            boot_difference = [boot_difference; difference(idx)]; %#ok<AGROW>
        end
        bias_boot(b) = mean(boot_difference);
        sd_boot = std(boot_difference,1);
        loa_lower_boot(b) = bias_boot(b)-1.96*sd_boot;
        loa_upper_boot(b) = bias_boot(b)+1.96*sd_boot;
    end

    bias_CI = prctile(bias_boot,[2.5 97.5]);
    loa_lower_CI = prctile(loa_lower_boot,[2.5 97.5]);
    loa_upper_CI = prctile(loa_upper_boot,[2.5 97.5]);

    output_row = table( ...
        string(device), numel(Y), n_subjects, bias, bias_CI(1), bias_CI(2), ...
        loa_lower, loa_upper, loa_lower_CI(1), loa_lower_CI(2), ...
        loa_upper_CI(1), loa_upper_CI(2), n_boot, ...
        'VariableNames', {'Device','NObservations','NSubjects','Bias', ...
        'BiasCI_Lower','BiasCI_Upper','LoA_Lower','LoA_Upper', ...
        'LoA_LowerCI_Lower','LoA_LowerCI_Upper','LoA_UpperCI_Lower', ...
        'LoA_UpperCI_Upper','ValidBootstraps'});

    points = table( ...
        repmat(string(device),height(Td),1), Td.SourceRow, Td.SubjectID, ...
        Y, z, mean_value, difference, ...
        'VariableNames', {'Device','SourceRow','SubjectID','rSO2','SjvO2', ...
        'PairMean','SourceDifference_rSO2_minus_SjvO2'});

    result = struct('mean_value',mean_value,'difference',difference, ...
        'bias',bias,'loa_lower',loa_lower,'loa_upper',loa_upper);
end
